name: nrn-rrn
channels:
  - conda-forge
  - defaults
dependencies:
  - click=7.1.2
  - fiona=1.8.18
  - gdal=3.1.4
  - geopandas=0.9.0
  - networkx=2.5
  - numpy=1.19.5
  - pandas=1.1.5
  - pip=21.0.1
  - python=3.9.2
  - pyyaml=5.4.1
  - requests=2.25.1
  - scipy=1.5.3
  - shapely=1.7.1
  - sphinx=3.5.1
  - tqdm=4.58.0
  - pip:
    - sphinx-intl==2.0.1
