name: egp
channels:
  - conda-forge
  - defaults
dependencies:
  - click=7.1.2
  - fiona=1.8.18
  - gdal=3.1.4
  - geopandas=0.9.0
  - matplotlib=3.4.3
  - numpy=1.19.5
  - pandas=1.1.5
  - pygeos=0.9
  - python=3.9.2
  - shapely=1.8.0
  - tabulate=0.8.9
  - tqdm=4.58.0
