name: egp
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1.3
  - fiona=1.8.21
  - gdal=3.5.0
  - geopandas=0.11.0
  - matplotlib=3.5.2
  - numpy=1.23.0
  - pandas=1.4.3
  - pygeos=0.12.0
  - python=3.9.13
  - pyyaml=6.0
  - shapely=1.8.2
  - tabulate=0.8.10
  - tqdm=4.64.0
