sources:
#  - ab
  - ab_c
  - ab_e
  - ab_n
  - ab_s
  - ab_w
#  - bc
  - bc_c
  - bc_n
  - bc_se
  - bc_sw
  - bc_v
#  - mb
  - mb_n
  - mb_s
#  - nb
  - nb_e
  - nb_n
  - nb_w
  - nl
#  - ns
  - ns_n
  - ns_s
  - nt
  - nu
#  - on
  - on_c
  - on_e
  - on_n
  - on_s
  - on_t
  - pe
#  - qc
  - qc_c
  - qc_e
  - qc_m
  - qc_n
  - qc_q
  - qc_s
  - qc_se
  - qc_w
#  - sk
  - sk_c
  - sk_n
  - sk_s
  - yt