sources:
#  - ab
  - ab_c
  - ab_e
  - ab_n
  - ab_s
  - ab_w
#  - bc
  - bc_c
  - bc_n
  - bc_se
  - bc_sw
  - bc_v
#  - mb
  - mb_brandon
  - mb_portage_la_prairie
  - mb_steinbach
  - mb_thompson
  - mb_winnipeg
#  - nb
  - nb_e
  - nb_n
  - nb_w
  - nl
#  - ns
  - ns_n
  - ns_s
  - nt
  - nu
#  - on
  - on_algoma
  - on_algonquin
  - on_bancroft
  - on_brampton
  - on_brantford
  - on_halton
  - on_hamilton
  - on_huron
  - on_kenora
  - on_kingston
  - on_london
  - on_mississauga
  - on_niagara
  - on_nipissing
  - on_oshawa
  - on_ottawa
  - on_peterborough
  - on_sarnia
  - on_scarborough
  - on_simcoe
  - on_sudbury
  - on_thunder_bay
  - on_timmins
  - on_toronto
  - on_waterloo
  - on_windsor
  - on_york
  - pe
#  - qc
  - qc_c
  - qc_e
  - qc_m
  - qc_n
  - qc_q
  - qc_s
  - qc_se
  - qc_w
#  - sk
  - sk_estevan
  - sk_humboldt
  - sk_kindersley
  - sk_lloydminster
  - sk_moose_jaw
  - sk_north_battleford
  - sk_prince_albert
  - sk_regina
  - sk_saskatoon
  - sk_swift_current
  - sk_tisdale
  - sk_yorkton
  - yt